apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: arc-test
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: fchimpan/arc-test

